ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.empty-block]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.package-comments]
[rule.range]
[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.var-declaration]

[rule.var-naming]
# Revive treats "time" as meaningless package name.
arguments = [[], [], [{ skipPackageNameChecks = true }]]

[rule.receiver-naming]
# Disabled, because it reports varying names in contexts, where varying names
# are expected. For example, it is convenient to use lhs/rhs pairs for Equal
# method, but it is odd to name receiver 'lhs' when method operates on single
# instance.
Disabled=true
